name: Diamusk
favicon: null
layout_spectrum: 0.9567759679630399
typography_spectrum: 0.36654422245919704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8945324604865164
  lightness: 0.8717230570036918
  saturation: 0.17728111194446683
  rhythmicContrast: 0.6185795846395195
purpose: []
