name: Diamusk
favicon: null
layout_spectrum: 0.95615
typography_spectrum: 0.07998
title: alias Adisa Zvekić
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b2d53'
    - '#010201'
    - '#94bfb5'
    - '#bef1de'
    - '#717a43'
  brandStrength: 0.8945324604865164
  lightness: 0.8717230570036918
  saturation: 0.17728111194446683
  rhythmicContrast: 0.75
purpose: []
